### PR TITLE
Log and continue rather than die when socket accept fails

### PR DESCRIPTION
**Pull request by andrewvc**
Fixes https://github.com/logstash-plugins/logstash-input-tcp/issues/59

### CODE REVIEW

**Comment by jakelandis** [comment]
Does the non-SSL implementation behave correctly ?

**Comment by andrewvc** [comment]
@jakelandis I believe it will? See: https://github.com/logstash-plugins/logstash-input-tcp/blob/master/src/main/java/org/logstash/tcp/InputLoop.java#L48

**Comment by andrewvc** [comment]
Refactored the tests in the latest commit to actually check port #s before opening them.

Also, the master / 6.x branches are failing due to https://github.com/elastic/logstash/pull/8097 but should not be blockers.

**Comment by jakelandis** [comment]
Still LGTM

**Pull request closed without merging**
