### PR TITLE
Add chained certificate support

### PR DESCRIPTION
**Pull request by cspenceiv**
This update does not require any additional input. It only expects to find the root and intermediate CAs appended to the end of the ssl_cert file.

This will potentially fix issue #3 and part of #9.

### CODE REVIEW

**Comment by cspenceiv** [comment]
Just added commit 0962c0a. I accidentally left off a line of the source. This solution should now work.

**Comment by cspenceiv** [comment]
Merged commits from upstream.

**Comment by purbon** [comment]
Thanks @cspenceiv for your contribution, I'm working on getting some test for your PR and merge them manually.

**Comment by purbon** [comment]
Closing this in favor of https://github.com/logstash-plugins/logstash-input-tcp/pull/28 that include this changes, more, and include tests.

**Pull request closed without merging**
