### PR TITLE
return instead of killing entire process

### PR DESCRIPTION
**Pull request by nneul**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by jordansissel** [comment]
I think the previous code is correct. We should raise an exception, but the behavior should be that the problematic connection is terminated.

By `killing entire process` you mean Logstash dies? Can you show the logs?

**Comment by nneul** [comment]
Nothing traps the IO Error, so the whole listener terminates and that in turn kills logstash itself. It looks like existing code has a catch for ErrNo::ECONNRESET only.

**Comment by nneul** [comment]
would 'raise IOError' and adding a 'rescue' that does nothing - equivalent to handling of EOFError in the current tcp code? Similar for other two plugins (syslog and log4j)?

Is there a better exception to use?

**Comment by nneul** [comment]
(re question on the syslog plugin) The (crash) is completely expected in this case - occurs if you configure the input to "use proxy protocol" and then make a non-proxy-protocol connection to the service. It just isn't exiting properly. It's primarily a question about the proper way to say "this connection is bad, I'm dropping it".  The IOError exception that was being raised resulted in the entire listener/plugin terminating, instead of just the individual connection.

**Comment by kares** [comment]
defunct - exception is expected to be catched at a higher level by LS. simply return-ing does not make sense ...

**Pull request closed without merging**
