### PR TITLE
mark deprecated data_timeout option as obsolete

### PR DESCRIPTION
**Pull request by jsvd**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by jakelandis** [comment]
Should the usage of ```ssl_cacert``` also be removed ?

https://github.com/logstash-plugins/logstash-input-tcp/blob/f382056a6957732a7cda9f71f6bb5eef4c7f43c5/lib/logstash/inputs/tcp.rb#L317

**Comment by jsvd** [comment]
@jakelandis this PR does just that: https://github.com/logstash-plugins/logstash-input-tcp/pull/82/files#diff-4440c0d7ed519b24cf7f535409052e90L317 :)

**Comment by jakelandis** [comment]
LGTM

**Comment by untergeek** [comment]
This is yielding build failures with JRuby 9K:
```
  1) LogStash::Inputs::Tcp should read plain with unicode
     Failure/Error: insist { event.get("message") } == "#{i} ☹"
     
     Insist::Failure:
       Expected "0 ☹", but got "4 ☹"
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/insist-1.0.0/lib/insist/assert.rb:8:in `assert'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/insist-1.0.0/lib/insist/comparators.rb:14:in `=='
     # ./spec/inputs/tcp_spec.rb:64:in `block in (root)'
     # ./spec/inputs/tcp_spec.rb:62:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
```

**Pull request merged**
