### PR TITLE
v2.0.5 Release Request

### PR DESCRIPTION
**Pull request by AlexBaker-**
* Tagged v2.0.5
* Bumped version in gemspec
* Bumped logstash-core dependency to coincide with today's release
* Updated CHANGELOG for 2.0.5, as well as missing 2.0.4
* Added myself to CONTRIBUTORS ;)

### CODE REVIEW

**Comment by AlexBaker-** [comment]
Also, sorry for the multiple commits.  I noob'd a little, pardon me. >_>

**Comment by purbon** [comment]
@AlexBaker- you can squash it :+1:, do you know how to make it?

**Comment by AlexBaker-** [comment]
Negative, Ghost Rider.  Docs, pl0x?

**Comment by purbon** [comment]
just use ```$ git rebase -i HEAD~N``` where N is the number of commits you want to squash, then select squash for each commit you want to group.

**Comment by purbon** [comment]
@AlexBaker- I can squash it myself if this makes your life easier, does this works for you?

**Comment by purbon** [comment]
Merged manually https://github.com/logstash-plugins/logstash-input-tcp/commit/5637bf7dc2f8466f8abdc9b897c072ebf0c43b4e

**Comment by AlexBaker-** [comment]
Thanks!

**Pull request closed without merging**
